### ISSUE TITLE
Skeleton from a box ?

### ISSUE THREAD

**Issue by CaptainJeffo** [Microsoft/RoomAliveToolkit#54]
Hello,

While testing the recognition of non human moving objects, we did discover a strange artefact.

In the screenshot you see on the left the skeleton of a actor. He keeps a approx. 30X50X2 cm isomo plate on a stick (middle of the screen).  At a certain moment both became joined and the box started to display a 'crawling' skeleton.... 

Looks like the skeleton recognition behave not accurate. Can this be avoided?

![screenshot 2](https://cloud.githubusercontent.com/assets/12197507/25182000/8d7b6872-2513-11e7-9299-598afc403b20.png)

:-)
Jan

**Comment by hbenko** [comment]
Short answer is no. This is simply the behavior of the Kinect skeletal tracker which is not always perfect. An idea you might want to try is to filter skeletons based on whether they report a valid face or not. That would eliminate your plate becoming a valid skeleton.
