### ISSUE TITLE
Kinect Version?

### ISSUE THREAD

**Issue by DybdeKameraBruger** [Microsoft/RoomAliveToolkit#58]
As it is for now, you are supporting the Kinect V2. Will you in future releases support a new version of the Kinect? And do you know if a new version is on the table?

**Comment by hbenko** [comment]
No current plans to support any different version of Kinect. We will re-evaluate that if new/other cameras become available. 
It would be a great community project to enable the use of Zed cameras or Intel RealSense cameras in our toolkit.
