### ISSUE TITLE
How to make a RoomScene not a black background?

### ISSUE THREAD

**Issue by HealerSu** [Microsoft/RoomAliveToolkit#60]
Hello,everyone,I have run the one projector and one kinect scene successfully,and i can see the virtual3Dmodels move and the virtualTexutures in the Game Window but with a black background,how can i make a meanful background to replace the black background?Hope someone can tell me ,keep waitting for the anwser,thank u very much!
![image](https://cloud.githubusercontent.com/assets/23717209/26338254/35c0efe0-3fb1-11e7-812a-0d85ede03bb3.png)

**Comment by hbenko** [comment]
If you simply want to change the color of the background, look into RATUserView script... there are two color pickers in the Inspector for exactly those purposes. 

If you want to render the static background with a different texture, then look into the RATProjectionPass for your User (for Static Surfaces). You will have to use/write a different shader for your User View Shader and link it appropriately there.

**Comment by HealerSu** [comment]
@hbenko Thank u for the answer,i changed the user view shader to "Standard" and now i can see the virtual wall in the GameWindow.
