### ISSUE TITLE
When Building ProCamEnsemble I have error saying "Could not copy file because it was not found"

### ISSUE THREAD

**Issue by wderstine** [Microsoft/RoomAliveToolkit#61]
Hello, 
I haven't even started any kind of calibration yet. I'm just trying to build the solution so I can start.

Before building I have this in the Output window:
_The mappings for the solution could not be found.
The active solution has been temprorarily disconnected from source control because the server is unavailable. To attempt to reconnect to source control, close and then reopen the solution when the server is available._

After attempting to build I have this error for multiple .cso files: 

_Could not copy the file "C:\Users\wderstine\Downloads\RoomAliveToolkit-master\RoomAliveToolkit-master\ProCamCalibration\x64\Debug\DepthAndColorGS.cso" because it was not found._

I noticed that there are .hlsl files with the same names as all of these. Is there something I'm missing?

**Comment by thundercarrot** [comment]
Did the Shaders project build successfully? (Note you may need to install Visual C++ components; VS 2015 does not install them by default). Try building just the Shaders project.

The first message is strange because I thought I dealt with that a long time ago...

**Comment by wderstine** [comment]
I'm in visual 2017 because when trying to get the 2015 said that the C++ for 2015 was no longer available. After building the Shaders project:

1>------ Build started: Project: Shaders, Configuration: Debug x64 ------
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ========== 

Also it looks like Microsoft is making it so you have to have a subscription to get older versions now.

**Comment by thundercarrot** [comment]
VS2017 should work fine. Can you confirm that you installed Visual C++ when you installed Visual Studio? VS2017's installation dialog has many options. I'm not sure C++ is installed by default.

**Comment by wderstine** [comment]
I know when I first downloaded I didn't get it because it was so large. But for this I think that I just downloaded C++ components and was 4GB so I think it was what I needed. But I'll just wipe everything and re-install it and see if that fixes it.

**Comment by wderstine** [comment]
Okay it's working now. Sweet. Now that that's built I will let you know of any other problems if I come across them. Thank you @thundercarrot.
