### ISSUE TITLE
Solve failed - System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by masterchop** [Microsoft/RoomAliveToolkit#62]
I am not able to run the Solve i always get this error, i used to be able to run it, i did once but now it never works. Any ideas why?

`acquired depth image 65
acquired depth image 66
acquired depth image 67
acquired depth image 68
acquired depth image 69
acquired depth image 70
acquired depth image 71
acquired depth image 72
acquired depth image 73
acquired depth image 74
acquired depth image 75
acquired depth image 76
acquired depth image 77
acquired depth image 78
acquired depth image 79
acquired depth image 80
acquired depth image 81
acquired depth image 82
acquired depth image 83
acquired depth image 84
acquired depth image 85
acquired depth image 86
acquired depth image 87
acquired depth image 88
acquired depth image 89
acquired depth image 90
acquired depth image 91
acquired depth image 92
acquired depth image 93
acquired depth image 94
acquired depth image 95
acquired depth image 96
acquired depth image 97
acquired depth image 98
acquired depth image 99
Acquire complete
decoding Gray code images for projector 0, camera 0
elapsed time 1366
projecting depth points to color camera 0
rejected 4.054116% pixels for high variance
elapsed time 4324
elapsed time 4384
calibrating projector 0
RANSAC iteration 0
Solve failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at RoomAliveToolkit.Matrix.Copy(Matrix A) in C:\Users\Extreme Tech\Downloads\RoomAliveToolkit-master\ProCamCalibration\ProCamEnsembleCalibration\Matrix.cs:line 129
   at RoomAliveToolkit.ProjectorCameraEnsemble.CalibrateProjectorGroups(String directory) in C:\Users\Extreme Tech\Downloads\RoomAliveToolkit-master\ProCamCalibration\ProCamEnsembleCalibration\ProjectorCameraEnsemble.cs:line 741
   at RoomAliveToolkit.MainForm.CalibrateProjectorGroups() in C:\Users\Extreme Tech\Downloads\RoomAliveToolkit-master\ProCamCalibration\CalibrateEnsemble\MainForm.cs:line 1152
Solve complete`

**Comment by thundercarrot** [comment]
Try recreating your calibration .xml file.

**Comment by masterchop** [comment]
Wow!! that was fast!
here is the calibration info: [zip file](https://drive.google.com/file/d/0BxuvPQbtAwiAdGMzQ1FlYVZOVnM/view?usp=sharing)

**Comment by masterchop** [comment]
This only worked once, i have tried puting the projector closer or backward to the wall same with kinect.
i am trying with lights on and off, for i believe that because of solve failing the OBJ never get imported to unity but i can use then in other 3d tools like 3d builder.

**Comment by masterchop** [comment]
After trobleshooting this i change the location of the kinect to point to a big funiture about 2 meters away, even it was a dark surface that we know kinect has problems with it worked and i manage to build it.
every work with no problems, this is a matter of location of the kinect sensor. 
Now i have problems in unity but need to debug more before :) thanks
