### ISSUE TITLE
Is Kinect for Xbox 360 supported?

### ISSUE THREAD

**Issue by rythmium** [Microsoft/RoomAliveToolkit#63]
I need to test a RoomAlive project that my coworkers are working on, but I don't have a Kinect for Xbox One. I only have access to a friend's Kinect for Xbox 360. Is that supported? 

Thanks.

**Comment by hbenko** [comment]
You might be able to test some parts of the project without a live running Kinect. However, Kinect for Xbox 360 is not supported.
