### ISSUE TITLE
Object Reference 

### ISSUE THREAD

**Issue by Vahid1164** [Microsoft/RoomAliveToolkit#70]
Hi,

The program stops at line 168 when I am running the sample. The error is: 

Object reference not set to an instance of an object.

Would you kindly help?

Thanks!

**Comment by thundercarrot** [comment]
Sorry, could you give a little bit more information? i.e. which file?

Please note that the sample expects a command line argument (the config file created in the calibration process).

**Comment by Vahid1164** [comment]
Hi Andy:

Thanks so much for your reply. 

I did pass the config file location in the sample settings. The program passes the source acquisition part.

Here's a screenshot of what I can see:

![screenshot](https://user-images.githubusercontent.com/17069065/32196602-81225406-bd7e-11e7-96dd-b9adc2e5b464.jpg)

Thanks for your advice.
Best

**Comment by thundercarrot** [comment]
If you inspect the config file in a text editor, does everything look reasonable in the projector section? My hunch is that calibration did not complete successfully.

**Comment by Vahid1164** [comment]
Thanks, Andy!

Well, as the logs suggest, everything goes well in the calibration and solving processes. The projectors and cameras are well discovered by the toolkit as well.

I have 3 projectors connected to one computer and surrounded through an MSI Geforce graphics card. When creating a config file through CalibrateEnsemble, I select "1" for projectors (as they are all connected to one computer) and "3" for cameras (as there are three cameras connected to three different computers connected through a switch). 

Here's the "projector" part of my config file:

<projectors>
    <ProjectorCameraEnsemble.Projector>
      <cameraMatrix i:nil="true" />
      <displayIndex>0</displayIndex>
      <height>1024</height>
      <hostNameOrAddress>localhost</hostNameOrAddress>
      <lensDistortion i:nil="true" />
      <lockIntrinsics>false</lockIntrinsics>
      <name>Projector</name>
      <pose i:nil="true" />
      <width>3840</width>
    </ProjectorCameraEnsemble.Projector>
  </projectors>
</ProjectorCameraEnsemble>

Thanks for taking the time attend to this issue, Andy! I really appreciate it.

**Comment by thundercarrot** [comment]
Hmm there's no pose or calibration information for the projector in that config file. I would try creating a fresh one and try running calibration again. If you use the same camera and projector names you won't need to run Acquire again. If that doesn't work for you, zip up the directory and put it somewhere where I can download it and I will take a look.

**Comment by Vahid1164** [comment]
Andy,

Sorry for my slow message! I tried making a new calibration file, but it did not work.

Here' s the zipped folder:
https://www.dropbox.com/s/myavsaf3hrrsxh2/Roomalive.zip?dl=0

Thanks for taking the time to troubleshoot this issue.

**Comment by thundercarrot** [comment]
Thanks for posting the files. I took a look. It seems you have three projectors, yet Windows is configured to treat them as a single logical display? If so, that will cause the calibration to fail.

Tweak your setup so that each projector is its own display in Windows, so that when the Gray codes are displayed, you only see them on a single projector.

**Comment by Vahid1164** [comment]
Thank, Andy! It worked! I really appreciate your help and support.
Best,
Vahid

**Comment by thundercarrot** [comment]
Great to hear!
