### ISSUE TITLE
kinect server depth map to be smooth out gradual grayscale

### ISSUE THREAD

**Issue by UrbanSam** [Microsoft/RoomAliveToolkit#79]
Hi, maybe I know is it possible to get a smooth out grayscale depth map reference from the image link below on the left side.

Right side is the depthmap texture I got from RATKinectcClient pass from KinectV2Server.

[https://drive.google.com/open?id=1Uoq220-aNuyy--AEmgShYm1-IT3UDcfp](url)

**Comment by thundercarrot** [comment]
I'm not sure I understand the question. The right side seems to be the same as the left, only the mapping from 16 bit depth values to 8 bit gray values is different.

**Comment by UrbanSam** [comment]
Is it possible to get a 16bit depth value from RATKinectClient? I notice that in the currentDepthFrame.depthData has a data length of  434176. Where the DepthFrame in Kinect V2 SDK has 868352 in length. Is that the reason why?

**Comment by UrbanSam** [comment]
Nvm I think i use the wrong depth data,  once i change to currentDepthFrame.depthImage seem to display exactly same as the left image now. Thanks.
