### ISSUE TITLE
understanding about calibration result (depthToColorTransform&projector pose)

### ISSUE THREAD

**Issue by liyuebit** [Microsoft/RoomAliveToolkit#80]
![11](https://user-images.githubusercontent.com/24894806/42143524-070d6306-7de8-11e8-8544-1c65998bf3f1.png)

I draw the calibration result in OpenCV Viz module, and compare it with the pose I really put, I can see that the rotation matrix is right, because the orientationis looks like right. But the translation matrix is wrong, because left and right are reversed, and up and down are also reversed. Does this mean that the ‘’depthToColorTransform’’ and “projector pose” are defined in the coordinate system as Figure1 shows? I want to confirm that the coordinate system used in this program is as Figure1 or Figure2 shows.( I personally think it should be the first one.)
I need your help.
Thanks.

**Comment by thundercarrot** [comment]
That is correct. x left, y up, z forward.

**Comment by liyuebit** [comment]
OK, thundercarrot. Thank you for your prompt reply.
