### ISSUE TITLE
Body Tracking question

### ISSUE THREAD

**Issue by NPatch** [Microsoft/RoomAliveToolkit#83]
I haven't tried a multiple Kinect test yet due to lack of equipment.

Just to be sure, does RAT merge data for BodyTracking from all sensors in an ensemble? Or does the Body Tracking data come from the first sensor in the calibration only? In a 3x3 test, will the Body Tracking be the result of merging data from all 3 Kinects so it becomes truly 3D tracking inside the room?
Otherwise if it's just from the first sensor, it will still be subject to occlusion issues. Right?

**Comment by NPatch** [comment]
Also is at least depth data merged when fed into the Unity project? Or are all Kinect cams separate when it comes to their feeds, all the way?

**Comment by thundercarrot** [comment]
Yes if you just use one skeleton you will find occlusions. 

Take a look at RATKinectSkeleton.MergeSkeleton. It's a simple-minded approach but could be useful.

Meshes from multiple depth cameras are not merged into a single mesh. They are treated separately. In practice, if the calibration is good, this won't matter for projection mapping.

**Comment by NPatch** [comment]
Indeed, it works fine for now!
